name: Linux Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: ["Debug", "Release"]

    name: Linux ${{ matrix.build-type }}
    steps:
    - uses: actions/checkout@v2

    - name: Install Deps
      run: |
        sudo apt update
        sudo apt install libsdl2-dev libsdl2-ttf-dev libsdl2-mixer-dev

    - name: Build
      run: |
        mkdir -p out/${{ matrix.build-type }}
        cd out/${{ matrix.build-type }}
        cmake -DENABLE_X11=NO -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} ../../
        make

    - name: Test
      run: ctest --output-on-failure
      working-directory: out/${{ matrix.build-type }}

  build-x11:
    runs-on: ubuntu-latest

    name: Linux X11
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        mkdir -p out
        cd out
        cmake ../
        make

    - name: Test
      run: ctest --output-on-failure
      working-directory: out
